!     ESTE PROGRAMA SIMULA EL COMPORTAMIENTO DEL SISTEMA SOLAR USANDO DATOS REALES SOBRE LA EXCENTRICIDAD DE LAS ORBITAS, LAS DISTANCIAS Y LAS MASAS DE DE LOS DIFERENTES PLANETAS. PARA ELLO SE USARÁ EL ALGORITMO DE VERLET. EL COMPORTAMIENTO Y LA SIMULACIÓN SE VERA REPRESENTADO TENIENDO EN CUENTA UN MODELO GEOCENTRICO Y HELIOCENTRICO. ADEMAS SE COMPROBARA LA VALIDEZ DEL SIGUIENTE METODO MATEMATICO PROGRAMADO COMPARANDO LOS VALORES DE LOS PERIODOS REALES DE LOS PLANETAS CON RESPECTO A LOS REPRESENTADOS EN EL SIGUIENTE PROGRAMA. TAMBIEN SE COMPROBARÁ QUE EL MOMENTO ANGULAR Y LA ENERGÍA TOTAL SE MANTIENE CONSTANTE A LO LARGO DE TODO EL TIEMPO PARA CADA UNO DE LOS PLANETAS.

      PROGRAM EVOLPLAN

      IMPLICIT NONE
!     LOS DATOS DADOS PARA CADA PLANETA SON SU MASA (M), DISTANCIA AL SOL (R) Y VELOCIDAD ORBITAL INICIAL(V). AQUELLOS CON CONNOTACION -D SON LAS VARIABLES RESCALADAS, Y AQUELLOS CON CONNOTACION -V SON PARA GUARDAR LAS VARIACIONES EN INCREMENTOS H EN EL ALGORTIMO DE VERLET Y PODER MOSTRARLO GRAFICAMENTE. LOS QUE TIENEN -VD SON LOS VALORES DE LAS MAGNITUDES CALCULADAS CON -V PERO VOLVIENDO A LA ESCALA ORIGINAL.
      INTEGER*8:: I, J, K, DIV
      REAL*8:: T, H, TD, HD, TS
      REAL*8:: PI, G, MS, C
      REAL*8, DIMENSION(1:10):: M, R, V, MD, RD, VD, PER
!     A ES LA ACELERACIÓN RESULTANTE PARA CADA UNA DE LAS POSICIONES RV QUE SE VA A USAR EN EL ALGORITMO DE VERLET. Y RG SON TODAS LAS POSICIONES PLANETARIAS CONSIDERANDO UN MODELO GEOCÉNTRICO.
!     LAS MATRICES SON TRIDIMENSIONALES YA QUE SE VA A GUARDAR LA POSICIÓN DE UN VECTOR EN EL EJE X, LA POSICIÓN DE UN VECTOR EN EL EJE Y Y SU VARIACIONES A LO LARGO DEL TIEMPO, DE TAL FORMA QUE -(I, J, K) LOS GUARDA RESPECTIVAMENTE. 
      REAL*8, DIMENSION(:,:,:), ALLOCATABLE:: RV, VV, A, RG
      REAL*8, DIMENSION(:,:,:), ALLOCATABLE:: RVD
      
!     DEFINIMOS LOS PARÁMETROS/CONSTANTES UTILIZADOS A LO LARGO DEL PROGRAMA CON SUS CORRESPONDIENTES UNIDADES.
      PARAMETER(PI = 4*ATAN(1.D0))
      PARAMETER(G = 6.67D-11) !NM²/KG², ES LA CONSTANTE GRAVITATORIA.
      PARAMETER(MS = 1.99D30) !KG, ES LA MASA SOLAR.
      PARAMETER(C = 1.496D11)     !M, ES LA DISTANCIA TIERRA-SOL.

      WRITE(6,*) "-----------------------------------------------------"
      WRITE(6,*) " "
      WRITE(6,*) " "
      WRITE(6,*) " "

      WRITE(6,*) "ESTE PROGRAMA SIMULA EL MOVIMIENTO  DE LOS PLANETAS"
      WRITE(6,*) "DEL SISTEMA SOLAR CONOCIENDO LA CONDICION INICIAL"
      WRITE(6,*) "DE CADA UNO DE ELLOS."
      WRITE(6,*) "Y SIGUIENDO UN ALGORITMO DE VERLET DURANTE UN TIEMPO:"
      WRITE(6,*) "T, QUE AUMENTA EN INCREMENTOS DE TIEMPO: H. "
      
      WRITE(6,*) " "
      WRITE(6,*) " "
      WRITE(6,*) " "
      WRITE(6,*) "-----------------------------------------------------"
      
!     SE HAN UTILIZADO SUBRUTINAS A LO LARGO DEL PROGRAMA PARA DEJAR LA PARTE DEL CODIGO PRINCIPAL LO MAS LIMPIO POSIBLE.
!     SE PROCEDE A INTRODUCIR LOS DATOS CORRESPONDIENTES A LOS PLANETAS:
!     EL ORDEN IRÁ DESCRITO POR EL ORDEN DESCRITO EN LA PÁGINA WEB: NSSDC.GSFC.NASA.GOV/PLANETARY/FACTSHEET/ EN EL SIGUIENTE ORDEN: SOL - 1, MERCURIO - 2, VENUS - 3, TIERRA - 4, LA LUNA SE OBVIA, MARTE - 5, JUPITER - 6, SATURNO - 7, URANO - 8, NEPTUNO - 9 Y PLUTÓN -10. AUNQUE PLUTÓN NO ES CONSIDERADO UN PLANETA DADO LOS CORRESPONDIENTES DATOS SE VA A CONSIDERAR EN EL PROGRAMA Y EN LOS CORRESPONDIENTES CÁLCULOS.

      CALL DATOSPLAN
      WRITE(6,*) "-----------------------------------------------------"

!     REALIZAMOS LOS CORRESPONDIENTES CALCULOS Y GUARDAMOS RESULTADOS.

      CALL EVOLVERLET
      WRITE(6,*) "-----------------------------------------------------"
      
!     AHORA SE VA A PROCEDER A MOSTRAR EL PERIODO Y LA CONSERVACION DEL MOMENTO ANGULAR Y LA ENERGIA TOTAL PARA CADA UNO DE LOS PLANETAS:
      WRITE(6,*) " "
      WRITE(6,*) "POSTERIORMENTE SE PROCEDE A DEMOSTRAR EL PERIODO,"
      WRITE(6,*) "Y LA CONSERVACION DEL MOMENTO Y LA ENERGIA TOTAL."
      WRITE(6,*) " "
      WRITE(6,*) " "

      CALL PERPLAN
      CALL MOMENPLAN
      CALL ENERPLAN
      
      STOP

      CONTAINS
      
      SUBROUTINE DATOSPLAN
!     CÓMO EL EJERCICIO TE PIDE EXPRESAMENTE QUE SEA TODO PARA EL SISTEMA SOLAR LO VAMOS A HACER DE LA SIGUIENTE MANERA, PERO SI FUERA UN PROGRAMA QUE SIMULASE EL MOVIMIENTO PARA UN SISTEMA ARBITRARIO SE PREGUNTARÍA Y COGERÍA DATOS POR PANTALLA CON RESPECTO AL NUMERO DE PLANETAS, CONDICIONES INCIALES, ETC...
      WRITE(6,*) "SE CONSIDERAN LOS SIGUIENTES COMPONENTES PARA " 
      WRITE(6,*) "EL SISTEMA SOLAR: SOL - 1, MERCURIO - 2, VENUS - 3," 
      WRITE(6,*) "TIERRA - 4, LA LUNA SE OBVIA, MARTE - 5, JUPITER - 6,"
      WRITE(6,*) "SATURNO - 7, URANO - 8, NEPTUNO - 9 Y PLUTÓN -10"
!     DATOS PARA LAS MASAS M(I) EN KG, LAS DISTANCIAS R(I) EN KM Y LAS VELOCIDADES V(I) EN KM/S.

!     PARA EL SOL.
      M(1) = MS
      R(1) = 0.D0
      V(1) = 0.D0
      
!     PARA MERCURIO.      
      M(2) = 0.33D24
      R(2) = 57.9D9
      V(2) = 47.4D3
      
!     PARA VENUS.      
      M(3) = 4.87D24
      R(3) = 108.9D9
      V(3) = 35D3

!     PARA LA TIERRA.
      M(4) = 5.97D24
      R(4) = C
      V(4) = 29.8D3

!     PARA MARTE.
      M(5) = 0.642D24
      R(5) = 228D9
      V(5) = 24.1D3
      
!     PARA JUPITER.
      M(6) = 1898D24
      R(6) = 778.5D9
      V(6) = 13.1D3
      
!     PARA SATURNO
      M(7) = 568D24
      R(7) = 1432D9
      V(7) = 9.7D3
      
!     PARA URANO.
      M(8) = 86.8D24
      R(8) = 2867D9
      V(8) = 6.8D3
      
!     PARA NEPTUNO.
      M(9) = 102D24
      R(9) = 4515D9
      V(9) = 5.4D3
      
!     PARA PLUTON.      
      M(10) = 0.013D24
      R(10) = 5906.4D9
      V(10) =  4.7D3

      WRITE(6,*) " "
      WRITE(6,*) "LOS DATOS INICIALES INTRODUCIDOS SON:"
      DO I = 1, 10

         WRITE(6,*) " "
         WRITE(6,*) "- PARA I =", I
         WRITE(6,*) "M(I)=", M(I), "KG."
         WRITE(6,*) "R(I)=", R(I), "M."
         WRITE(6,*) "V(I)=", V(I), "M/S."
         
      END DO

!     PARA OBTENER LOS RESULTADOS TANTO T CÓMO H SON COMPLETAMENTE ARBITRARIOS, LOS PEDIMOS POR PANTALLA: (DEBEN DE SER CONSECUENTES CON LA SITUACION EN LA QUE NOS HALLAMOS, SI EL PERIODO TERRESTRE ES DE 1 AÑO, INTRODUCIR POR PANTALLA EL TIEMPO EN SEGUNDOS VA DAR COMO RESULTADO QUE TENGAMOS QUE ESCRIBIR VALORES MUY MUY GRADES, POR LO QUE SE VAN A PEDIR EN AÑOS, LUEGO SE PASA A SEGUNDOS, Y H POR OTRO LADO YA SE CONSIDERA EN SEGUNDOS.)
!     IMPORTANTE RECORDAR QUE RECONOCEMOS COMO T0 EL MOMENTO 0 SEGUNDOS Y T ES EL TIEMPO TRANSCURRIDO ENTRE 0 Y UN TIEMPO DADO CUALQUIERA T, ADEMÁS DE QUE EN CUALQUIER CASO SE CONSIDERA QUE TODOS LOS PLANETAS COMIENZAN SU MOVIMIENTO EN UN EJE HORIZONTAL X = 0.

      WRITE(6,*) " "
      WRITE(6,*) " "
      WRITE(6,*) "-----------------------------------------------------"
      WRITE(6,*) " "
      WRITE(6,*) " "    
      WRITE(6,*) "INTRODUZCA T EN DÍAS:"
      WRITE(6,*) "(TEN EN CUENTA QUE EL PERIODO DE MERCURIO ES 88 DÍAS"
      WRITE(6,*) "Y EL PERIODO DE PLUTON SON 90560 DÍAS.)"
      WRITE(6,*) " "
      READ(5,*) T
      WRITE(6,*) " "
      WRITE(6,*) "Y H TAMBIEN EN DIAS:"
      WRITE(6,*) "(CUANTO MENOR SEA H, MAYOR PRECISION TENDRAN LOS "
      WRITE(6,*) "RESULTADOS, PERO TEN EN CUENTA QUE TAMBIEN MAS "
      WRITE(6,*) "CALCULO TENDRA QUE REALIZAR EL ORDENADOR. "
      WRITE(6,*) "EL LIMITE DE DIVISIONES A RELIZAR SE HA COLOCADO "
      WRITE(6,*) "EN 1 MILLON.) "
      WRITE(6,*) " "
 1    READ(5,*) H

      DIV = T/H
!      WRITE(6,*) DIV, TS
      
      IF (DIV.LT.1) THEN
         WRITE(6,*) " "
         WRITE(6,*) "LA DIVISION TEMPORAL ES MENOR QUE 1"
         WRITE(6,*) "POR FAVOR, REDUZCA EL VALOR DE H."
         WRITE(6,*) " "
         WRITE(6,*) "VUELVA A ESCRIBIR H EN DÍAS:"
         GO TO 1
      ELSE IF (DIV.GT.1000000) THEN
         WRITE(6,*) " "
         WRITE(6,*) "LA DIVISION TEMPORAL ES DEMASIADO GRANDE"
         WRITE(6,*) "POR FAVOR, AUMENTE EL VALOR DE H."
         WRITE(6,*) " "
         WRITE(6,*) "VUELVA A ESCRIBIR H EN DÍAS:"
         GO TO 1
      ELSE
         WRITE(6,*) " "
         WRITE(6,*) "SE VAN A REALIZAR APROXIMADAMENTE:", DIV
         WRITE(6,*) "DIVISIONES DEL TIEMPO."
         GO TO 2
      END IF   
      
 2    END SUBROUTINE DATOSPLAN

      SUBROUTINE EVOLVERLET
      
!     AUNQUE PODAMOS INTRODUCIR UNIDADES DE TIEMPO EN NUMEROS REALES SE VA A CONSIDERAR LAS DIVISIONES DEL TIEMPO Y EL PASO DEL TIEMPO EN UNIDADES ENTERAS CASI QUE OBVIANDO LOS DECIMALES YA QUE EN REALIDAD DADO LAS GRANDES MAGNITUDES DE TIEMPO EN LAS QUE SE VA A TRABAJAR CASI QUE LOS DECIMALES DAN IGUAL.
      INTEGER*8:: L
      REAL*8::  MODR, MODR2
      INTEGER*8, DIMENSION(1:2):: SUMA
      REAL*8, DIMENSION(:,:,:), ALLOCATABLE:: ALPHA

      ALLOCATE(RV(1:10,1:2,1:DIV))
      ALLOCATE(VV(1:10,1:2,1:DIV))
      ALLOCATE(A(1:10,1:2,1:DIV))
      ALLOCATE(RG(1:10,1:2,1:DIV))
      ALLOCATE(ALPHA(1:10,1:2,1:DIV))
      ALLOCATE(RVD(1:10,1:2,1:DIV))

!     DADO AL GRAN TAMAÑO DE LOS NUMEROS LOS REDIMENSIONAMOS PARA REALIZAR LOS CALCULOS CORRESPONDIENTES CORRECTAMENTE UTILIZANDO EL ALGORITMO DE VERLET A LO LARGO DEL RESTO DEL PROGRAMA. REDIMENSIONAREMOS: M, R, T Y H. DE ESTA FORMA Y COMO VAMOS A MOSTRAR A CONTINUACIÓN SE VA A TENER LOS DATOS SIN REDIMENSIONAR EN LOS VECTORES M, R..., LOS VECTORES REDIMENSIONADOS MD, RD... Y POR ÚLTIMO LOS QUE SE VAN A USAR PARA REALIZAR CÁLCULOS RV Y VV.
!     RECORDEMO QUE VECTORIALMENTE LOS VECTORES POSICION Y VELOCIDAD SON PERPENDICULARES. 1 - DIRECCIÓN DE X Y 2 - DIRECCION DE Y.
      DO I=2, 10
         RD(I) = R(I)/C
         MD(I) = M(I)/MS
         VD(I) = V(I)/((G*MS/C)**(0.5D0))
         RV(I,1,1) = RD(I)
         VV(I,2,1) = VD(I)
!        VV(I,2,1) = (G*MS/RD(I))**(0.5D0)
         RV(I,2,1) = 0.D0   
         VV(I,1,1) = 0.D0
!        WRITE(6,*) I,RD(I),MD(I),RV(I,1,1),VV(I,2,1),RV(I,2,1),VV(I,1,1)
      END DO
      
      TD = ((G*MS/C**3)**(0.5D0)) * (T*3600)
      HD = ((G*MS/C**3)**(0.5D0)) * (H*3600)
!      WRITE(6,*) TD, HD, TD/HD

!     EL SOL SIEMPRE SE MANTIENE EN SU POSICIÓN INICIAL:
      DO J = 1, 2
         DO K = 1, DIV
            RV(1, J, K) = 0.D0
            VV(1, J, K) = 0.D0
            A(1, J, K) = 0.D0
         END DO   
      END DO   
      
!     EL ALGORITMO DE VERLET ES EL SIGUIENTE, PARA EL MODELO HELIOCÉNTRICO:
      
!     A CADA POSICIÓN INICIAL SE LE ASIGNA UNA ACELERACIÓN INICIAL.
  !     POR CADA INSTANTE DE TIEMPO ENCONTRAMOS QUE LA ACELERACIÓN VARIA SIGUIENDO LA ECUACIÓN SUMATORIA DESCRITA EN PLANETAS-SLIDESV1.PDF.
!     SE VA A UTILIZAR DE MANERA AUXILIAR UN REAL CONOCIDO COMO SUMA QUE CUATIFICARA LA SUMA DE LOS VECTORES EN LA ACELERACIÓN Y SE REINICIARÁ PARA CADA CICLO DE TIEMPO K, Y PARA CADA CICLO DEL SUMATORIO:
      DO I = 2, 10
         
         DO J = 1, 2
            A(I, J, 1) = 0.D0
         END DO   
         
         DO L = 1, 10
        
            IF (L.NE.I) THEN
               
               MODR=(RV(I,1,1)-RV(L,1,1))**2+(RV(I,2,1)-RV(L,2,1))**2
               MODR2 = MODR**1.5D0
               
               DO J = 1, 2 
             A(I, J, 1)=A(I, J, 1)-(MD(L)*(RV(I,J,1)-RV(L,J,1)))/(MODR2)
               END DO
          
            END IF

            MODR = 0.D0
            MODR2 = 0.D0
            
         END DO
         WRITE(6,*) A(I,1,1), A(I,2,1)
      END DO
      
       
      
!     -------------------------------------------------------------------------------------------------------------------------
!     EN ESTA PARTE SE HA PROBADO UN ALGORTIMO QUE CALCULA LA ACELERACIÓN COMO FUERZA GRAVITATORIA PROCEDENTE UNICAMENTE POR EL SOL PARA ENCONTRAR EL ERROR.
!      DO I = 2, 10
!          DO J = 1, 2
!      A(I, J, 1) =-MS*G*RV(I,J,1)/((RV(I,1,1)**2+RV(I,2,1)**2)**(1.5D0))
!         END DO   
!      END DO   
 
!     -------------------------------------------------------------------------------------------------------------------------         
!     SE GUARDAN LAS VARIACIONES DE LAS MAGNITUDES A CADA VARIACION DE TIEMPO CONOCIDA POR EL VECTOR TT.
!        WRITE(6,*) I,RD(I),MD(I),RV(I,1,1),VV(I,2,1),RV(I,2,1),VV(I,1,1)
      DO K=1, DIV - 1

!     PRIMERO EVALUMOS RV Y ALPHA CONOCIENDO VV Y A INICIALES:
         DO I = 2, 10
            DO J = 1, 2
             ALPHA(I,J,K) = VV(I,J,K) + (HD/2.D0)*A(I, J,K)
             RV(I,J, K+1) = RV(I,J, K) + ALPHA(I,J,K)*HD
            END DO
         END DO 
!            WRITE(6,*) I, K, RV(I,1, K), RV(I,2, K)
!            WRITE(6,*) I, K, RV(I,1, K+1), RV(I,2, K+1)

!     OBTENEMOS LA SIGUIENTE ACELERACIÓN Y LA NUEVA VELOCIDAD EN EL SIGUIENTE CICLO:

         DO I = 2, 10
         
         DO J = 1, 2
            A(I, J, K+1) = 0.D0
         END DO   
         
         DO L = 1, 10
        
            IF (L.NE.I) THEN
          MODR=(RV(I,1,K+1)-RV(L,1,K+1))**2+(RV(I,2,K+1)-RV(L,2,K+1))**2
          MODR2 = MODR**1.5D0
               DO J = 1, 2
         A(I,J,K+1)=A(I,J,K+1)-(MD(L)*(RV(I,J,K+1)-RV(L,J,K+1)))/(MODR2)
               END DO
            END IF

            MODR = 0.D0
            MODR2 = 0.D0
            
         END DO
         END DO
         
         DO I = 2,10
            DO J = 1,2
            VV(I,J,K+1) = ALPHA(I, J, K) + (HD/2.D0)*A(I, J, K+1)
            END DO
         END DO
         
      END DO
         
 

!     HAY QUE TENER EN CUENTA QUE TODAS LAS POSICIONES FUERON ANTERIORMENTE REESCALADAS, POR ESO PRIMERO VAMOS A HACER EL PROCESO CONTRARIO PARA OBTENER VALORES REALES DE LAS CORRESPONDIENTES MEDIDAS.

      DO I = 1, 10
         DO J = 1, 2
            DO K = 1, DIV
               RVD(I,J,K)=RV(I,J,K) * C
            END DO
         END DO   
      END DO
      
!     PARA EL MODELO GEOCÉNTRICO DEL MOVIMIENTO DE LOS PLANETAS SIMPLEMENTE SE VA A CONSIDERAR QUE LA TIERRA ES EL CENTRO DE MOVIMIENTO, Y ESTO ES FACILMENTE OBTENIBLE RESTANDOLE LA DISTANCIA TIERRA-SOL A TODAS LAS POSICIONES PLANETARIAS. AUNQUE HAY QUE TENER EN CUENTA QUE ESTA ES VARIABLE Y POR TANTO SE TENDRAN EN CONSIDERACIONES LAS MISMAS VARIACIONES GUARDADAS EN EL VECTOR RV(I,J) UTILIZADO EN EL ALGORITMO DE VERLET, REALIZANDO DE NUEVO EL MISMO PERO CON LAS NUEVAS POSICIONES.
      DO I = 1, 10
         DO J = 1, 2
            DO K = 1, DIV
               RG(I, J, K) = RVD(I, J, K) - R(4)
            END DO   
         END DO
      END DO   

!     PARA EL MOVIMIENTO CENTRADO EN EL SOL.
      OPEN(UNIT = 20, FILE = 'VXY-MovHelSOL.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(20,*) RVD(1, 1, K), RVD(1, 2, K)   
      END DO   
      CLOSE(20)

      OPEN(UNIT = 21, FILE = 'VXY-MovHelMER.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(21,*) RVD(2, 1, K), RVD(2, 2, K) 
      END DO
      CLOSE(21)
      
      OPEN(UNIT = 22, FILE = 'VXY-MovHelVEN.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(22,*) RVD(3, 1, K), RVD(3, 2, K)   
      END DO      
      CLOSE(22)

      OPEN(UNIT = 23, FILE = 'VXY-MovHelTIE.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(23,*) RVD(4, 1, K), RVD(4, 2, K)   
      END DO
      CLOSE(23)

      OPEN(UNIT = 24, FILE = 'VXY-MovHelMAR.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(24,*) RVD(5, 1, K), RVD(5, 2, K)    
      END DO      
      CLOSE(24)

      OPEN(UNIT = 25, FILE = 'VXY-MovHelJUP.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(25,*) RVD(6, 1, K), RVD(6, 2, K)
      END DO      
      CLOSE(25)

      OPEN(UNIT = 26, FILE = 'VXY-MovHelSAT.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(26,*) RVD(7, 1, K), RVD(7, 2, K)  
      END DO      
      CLOSE(26)

      OPEN(UNIT = 27, FILE = 'VXY-MovHelURA.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(27,*) RVD(8, 1, K), RVD(8, 2, K)  
      END DO      
      CLOSE(27)

      OPEN(UNIT = 28, FILE = 'VXY-MovHelNEP.dat', STATUS = 'UNKNOWN')
       DO K = 1, DIV
          WRITE(28,*) RVD(9, 1, K), RVD(9, 2, K)
      END DO     
      CLOSE(28)

      OPEN(UNIT = 29, FILE = 'VXY-MovHelPLU.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(29,*) RVD(10, 1, K), RVD(10, 2, K)
      END DO      
      CLOSE(29)

!     PARA EL MOVIMIENTO CENTRANDONOS EN EL PLANETA TIERRA.
      OPEN(UNIT = 30, FILE = 'VXY-MovGeoSOL.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(30,*) RG(1, 1, K), RG(1, 2, K)   
      END DO   
      CLOSE(30)

      OPEN(UNIT = 31, FILE = 'VXY-MovGeoMER.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(31,*) RG(2, 1, K), RG(2, 2, K) 
      END DO
      CLOSE(31)
      
      OPEN(UNIT = 32, FILE = 'VXY-MovGeoVEN.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(32,*) RG(3, 1, K), RG(3, 2, K)   
      END DO      
      CLOSE(32)

      OPEN(UNIT = 33, FILE = 'VXY-MovGeoTIE.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(33,*) RG(4, 1, K), RG(4, 2, K)   
      END DO
      CLOSE(33)

      OPEN(UNIT = 34, FILE = 'VXY-MovGeoMAR.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(34,*) RG(5, 1, K), RG(5, 2, K)    
      END DO      
      CLOSE(34)

      OPEN(UNIT = 35, FILE = 'VXY-MovGeoJUP.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(35,*) RG(6, 1, K), RG(6, 2, K)
      END DO      
      CLOSE(35)

      OPEN(UNIT = 36, FILE = 'VXY-MovGeoSAT.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(36,*) RG(7, 1, K), RG(7, 2, K)  
      END DO      
      CLOSE(36)

      OPEN(UNIT = 37, FILE = 'VXY-MovGeoURA.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(37,*) RG(8, 1, K), RG(8, 2, K)  
      END DO      
      CLOSE(37)

      OPEN(UNIT = 38, FILE = 'VXY-MovGeoNEP.dat', STATUS = 'UNKNOWN')
       DO K = 1, DIV
          WRITE(38,*) RG(9, 1, K), RG(9, 2, K)
      END DO     
      CLOSE(38)

      OPEN(UNIT = 39, FILE = 'VXY-MovGeoPLU.dat', STATUS = 'UNKNOWN')
      DO K = 1, DIV
         WRITE(39,*) RG(10, 1, K), RG(10, 2, K)
      END DO      
      CLOSE(39)

      WRITE(6,*) " "
      WRITE(6,*) " "
      WRITE(6,*) " "
      WRITE(6,*) "SE CALCULARON LAS VARIACIONES DE LOS EJES X E Y, Y"
      WRITE(6,*) "LOS RESULTADOS SE HAN GUARDADO EN LA MISMA CARPETA"
      WRITE(6,*) "DEL PROGRAMA CON LOS SIGUIENTES NOMBRES: "
      WRITE(6,*) "Y VXY-MOVHELNOM Y VXY-MOVGEONOM, PARA EL"
      WRITE(6,*) "MOVIMIENTO HELIOCENTRICO Y GEOCENTRICO"
      WRITE(6,*) "RESPECTIVAMENTE PARA CADA UNO DE LOS PLANETAS."     
      WRITE(6,*) " "
      WRITE(6,*) " "
      WRITE(6,*) " "
            
      END SUBROUTINE EVOLVERLET

      SUBROUTINE PERPLAN

!     EN EL SIGUIENTE VECTOR SE VA A GUARDAR LOS VALORES DE X E Y CALCULADOS EN EL ALGORITMO DE VERLET MÁS GRANDE A LO LARGO DE TODOS LOS CALCULADOS.
      REAL*8, DIMENSION(1:10):: XYMG

      DO I = 2, 10
         DO K = 1, DIV-1
            DO J = 1, 2
               IF (RVD(I, J, K+1).GE.RVD(I, J, K)) THEN
                  XYMG(I) = RVD(I, J, K+1)
               END IF       
            END DO   
         END DO
         PER(I) = 2*PI*SQRT(XYMG(I)**3/G*MS)
      END DO   

      WRITE(6,*) "1."
      WRITE(6,*) "SEAN LOS PERIODOS PARA CADA PLANETA CON RESPECTO"
      WRITE(6,*) "AL CALCULADO RESPECTIVAMENTE EN DIAS, OBTENEMOS:"
      WRITE(6,*) " "
      WRITE(6,*) "- PARA MERCURIO: 88,", PER(2)
      WRITE(6,*) "- PARA VENUS: 224.7,", PER(3)
      WRITE(6,*) "- PARA TIERRA: 365.2,", PER(4)
      WRITE(6,*) "- PARA MARTE: 687,", PER(5)
      WRITE(6,*) "- PARA JUPITER: 4331,", PER(6)
      WRITE(6,*) "- PARA SATURNO: 10747,", PER(7)
      WRITE(6,*) "- PARA URANO: 30589,", PER(8)
      WRITE(6,*) "- PARA NEPTUNO: 59800,", PER(9)
      WRITE(6,*) "- PARA PLUTON: 90560,", PER(10)

      END SUBROUTINE PERPLAN

!     PARA LOS CALCULOS TANTO DEL MOMENTO COMO DE LA ENERGIA SE VAN A UTILIZAR LAS MAGNITUDES RESCALADAS MAS QUE NADA PARA ALIGERAR LA VELOCIDAD DEL PROGRAMA DE CALCULAR LOS CORRESPONDIENTES CALCULOS ADEMAS DE QUE COMO VAMOS A COMPROBAR QUE LA SUMA TOTAL DE LAS CORRESPONDIENTES MAGNITUDES ES IGUAL A 0, DA LO MISMO QUE ESTEN RESCALADOS PUES TODAS LAS MAGNITUDES ESTAN RESCALADAS EN PROPORCIONES IGUALES.

      SUBROUTINE MOMENPLAN

!     EN EL MISMO PROGRAMA SE VA A DEMOSTRAR QUE EL MOMENTO SE MANTIENE CONSTANTE CALCULANDO SU VALOR Y SUMANDOLO PARA TODOS LOS MOMENTOS EN LOS QUE SE HA CALCULADO LA POSICION Y VELOCIDAD. EL MOMENTO LO OBTENEMOS COMO EL PRODUCTO VECTORIAL ENTRE EL VECTOR DIRECTOR Y EL VECTOR MOMENTO LINEAL Q NO ES MAS Q LA MASA DE CADA PLANETA POR EL VECTOR VELOCIDAD.
      REAL*8, DIMENSION(1:10):: SUMMOM
      REAL*8, DIMENSION(1:10, 1:DIV):: MOM

      SUMMOM(1) = 0.D0
      
      DO I = 2, 10
         SUMMOM(I) = 0.D0
         DO K = 1, DIV
            MOM(I, K) = MD(I)*(RV(I,1,K)*VV(I,2,K)-RV(I,2,K)*VV(I,1,K))
            SUMMOM(I) = SUMMOM(I) + MOM(I,K) 
         END DO   
      END DO
      
      WRITE(6,*) " "
      WRITE(6,*) "2. "
      WRITE(6,*) "LA SUMA DE MOMENTOS PARA CADA UNO DE LOS PLANETAS ES:"
      WRITE(6,*) " "
      WRITE(6,*) "- PARA MERCURIO:", SUMMOM(2)
      WRITE(6,*) "- PARA VENUS:", SUMMOM(3)
      WRITE(6,*) "- PARA TIERRA:", SUMMOM(4)
      WRITE(6,*) "- PARA MARTE:", SUMMOM(5)
      WRITE(6,*) "- PARA JUPITER:", SUMMOM(6)
      WRITE(6,*) "- PARA SATURNO:", SUMMOM(7)
      WRITE(6,*) "- PARA URANO:", SUMMOM(8)
      WRITE(6,*) "- PARA NEPTUNO:", SUMMOM(9)
      WRITE(6,*) "- PARA PLUTON:", SUMMOM(10)

      END SUBROUTINE MOMENPLAN
      
      SUBROUTINE ENERPLAN
!     TMB EN EL MISMO PROGRAMA VAMOS COMPROBAR QUE LA ENERGIA SE MANTIENE CONSTANTE, PARA ELLO VAMOS A CALCULAR SU VALOR PARA CADA PLANETA Y SUMARLO, Y MOSTRARLOS POR PANTALLA. LA ENERGÍA CINÉTICA ES LA QUE SIEMPRE SE CALCULA, COMO UN MEDIO DE LA MASA DEL CORRESPONDIENTE PLANETA POR EL MODULO DEL VECTOR VELOCIDAD AL CUADRADO. LA ENERGÍA POTENCIAL ES LA PROCEDENTE DE LA FUERZA TOTAL COMO GRADIENTE DE UN POTENCIAL, POR TANTO TOMA UNA FORMA MUY PARECIDA A LA ECUACION UTILIZADA PARA OBTENER LA ACELERACION. LA ENERGIA TOTAL ES LA SUMA DE LAS DOS ANTERIORES.
      INTEGER*8:: L
      REAL*8:: PO, MODR
      REAL*8, DIMENSION(1:10):: ET
      REAL*8, DIMENSION(1:10,1:DIV):: EC, U

      DO I = 2, 10
         ET(I) = 0.D0
         DO K = 1, DIV
            DO L=1, 10
               PO = 0.D0
               MODR = 0.D0
               IF (I.NE.L) THEN
                MODR = (RV(L,1,K)-RV(I,1,K))**2+(RV(L,2,K)-RV(I,2,K))**2
                PO = G*(MD(I)*MD(K))/(SQRT(MODR))
               END IF   
               U(I,K)=U(I,K) + PO
            END DO   
            EC(I,K)=(M(I)/2)*((VV(I,1,K))**2+(VV(I,2,K))**2)

            ET(I) = ET(I) + U(I,K) + EC(I,K)
         END DO   
      END DO

      WRITE(6,*) " "
      WRITE(6,*) "3. "
      WRITE(6,*) "LA SUMA DE ENERGIA PARA CADA UNO DE LOS PLANETAS ES:"
      WRITE(6,*) " "
      WRITE(6,*) "- PARA MERCURIO:", ET(2)
      WRITE(6,*) "- PARA VENUS:", ET(3)
      WRITE(6,*) "- PARA TIERRA:", ET(4)
      WRITE(6,*) "- PARA MARTE:", ET(5)
      WRITE(6,*) "- PARA JUPITER:", ET(6)
      WRITE(6,*) "- PARA SATURNO:", ET(7)
      WRITE(6,*) "- PARA URANO:", ET(8)
      WRITE(6,*) "- PARA NEPTUNO:", ET(9)
      WRITE(6,*) "- PARA PLUTON:", ET(10)

      END SUBROUTINE ENERPLAN
      
      END PROGRAM EVOLPLAN
